ALTER TYPE "IntegrationProvider" ADD VALUE IF NOT EXISTS 'INSTAGRAM';
ALTER TYPE "IntegrationProvider" ADD VALUE IF NOT EXISTS 'TIKTOK';
ALTER TYPE "IntegrationProvider" ADD VALUE IF NOT EXISTS 'YOUTUBE';
ALTER TYPE "IntegrationProvider" ADD VALUE IF NOT EXISTS 'LINKEDIN';
